services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=product-service'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verySecret'
      - 'MYSQL_USER=myUser'
    ports:
      - '3306:3306'
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=inventory-service'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'